version: "3"
services:
  # Container of the frontend
  web:
    environment:
      # take care of an error
      - CHOKIDAR_USEPOLLING=true
    build:
      # where is the application
      context: .
      # whats the docker file
      dockerfile: Dockerfile.dev
    ports:
      # port mapping
      - "3000:3000"
    volumes:
      # What to exclude
      - /app/node_modules
      # <CorrentDir> : <ContainerWorkDir>
      - .:/app
  # Container of the tests
  tests:
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
